name: mazadxx
description: Offline-first auction-first ecommerce app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_animate: 4.5.2
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/auctions/
    - assets/images/wanted/
    - assets/images/avatars/
    - assets/data/
